// Generated by prepare-netlify-site.sh — 2026-06-02T14:25Z
window.LW_BROADCAST_SERVER_URL = 'https://streaming-server-production-d33c.up.railway.app';
window.LW_PUBLIC_RTMP_URL = 'rtmp://turntable.proxy.rlwy.net:35297/live';
window.LW_PUBLIC_HLS_BASE = 'https://streaming-server-production-d33c.up.railway.app/live';
window.LW_CONFIG_API_SECRET = '';
