#!/bin/bash
# Builds netlify-site/ — ONLY files needed for the public website (~500KB).
# Use this folder for Netlify drag-and-drop OR let Netlify build from Git.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/netlify-site"
API_URL="${BROADCAST_API_URL:-}"

rm -rf "$OUT"
mkdir -p "$OUT/css" "$OUT/js"

cp "$ROOT/index.html" "$OUT/"
cp "$ROOT/scripts/netlify-site.toml" "$OUT/netlify.toml"
cp "$ROOT/scripts/netlify-site-redirects" "$OUT/_redirects"
cp -R "$ROOT/css/"* "$OUT/css/"

# JS — skip tests and unused 5MB openapi spec
for f in "$ROOT/js/"*; do
  base=$(basename "$f")
  case "$base" in
    *test*|*Test*|openapi.json|bug-*.js|preservation-*.js|fix-verification*.js|connectivity-bug*.js|real-api-integration*.js|api.test.js)
      continue
      ;;
    *.md)
      continue
      ;;
  esac
  cp "$f" "$OUT/js/"
done

# Production API URL for Netlify visitors
cat > "$OUT/js/runtime-config.js" <<EOF
// Generated by prepare-netlify-site.sh — $(date -u +%Y-%m-%dT%H:%MZ)
window.LW_BROADCAST_SERVER_URL = '${API_URL}';
EOF

SIZE=$(du -sh "$OUT" | cut -f1)
echo "Created netlify-site/ ($SIZE)"
echo "BROADCAST_API_URL = ${API_URL:-(empty — set in Netlify env vars)}"
echo ""
echo "Next: Netlify → Deploys → Deploy manually → drag the netlify-site FOLDER"
echo "Or run: cd netlify-site && zip -r ../Loveworld-Netlify-Upload.zip ."
